### PR TITLE
fix: support global references

### LINKED ISSUE #5: Support global references
Our free-variable logic is backwards. We track all variables seen prior to a closure and use that to detect a free variable (an identifier that exists in the map), but this doesn't work for global references that have no declaration within a module.

To solve this, we should reverse the logic to detect free variables when an identifier doesn't exist in a map of all names declared within the closure itself.

### PR DESCRIPTION
**Pull request by sam-goodwin**
Fixes #5 

Our free-variable logic is backwards. We track all variables seen prior to a closure and use that to detect a free variable (an identifier that exists in the map), but this doesn't work for global references that have no declaration within a module.

This change reverses the logic to detect free variables when an identifier doesn't exist in a map of all names declared within the closure itself.

### CODE REVIEW

File: src/closure_decorator.rs [hunk 1]
```diff
@@ -321,10 +279,10 @@ impl VisitMut for ClosureDecorator {
 impl ClosureDecorator {
   fn register_stmt_if_func_decl(&mut self, stmt: &Stmt) -> Option<Stmt> {
     match stmt {
-      Stmt::Decl(Decl::Fn(func)) => Some(self.register_ast_stmt(
-        Box::new(Expr::Ident(func.ident.clone())),
-        self.parse_function_decl(&func),
-      )),
+      Stmt::Decl(Decl::Fn(func)) => {
+        let parse_func = self.parse_function_decl(&func);
+        Some(self.register_ast_stmt(Box::new(Expr::Ident(func.ident.clone())), parse_func))
```
Comment (sam-goodwin) [inline src/closure_decorator.rs:284]: this change was necessary because `self.parse_function_decl` now mutably borrows `self`.

**Comment by sam-goodwin** [comment]
Tested against functionless, I plan to add a test to this repo that checks out functionless and runs the tests - i can't do that until completing the SWC migration https://github.com/functionless/functionless/pulls

File: src/parse.rs [hunk 2]
```diff
@@ -180,126 +241,204 @@ impl ClosureDecorator {
...
+      Stmt::For(for_stmt) => {
+        // create a unique scope for the contents for the variables declared in the for-loop's initializer
+        self.vm.enter();
+
+        let init = for_stmt
+          .init
+          .as_ref()
+          .map(|init| match init {
+            VarDeclOrExpr::Expr(expr) => self.parse_expr(expr.as_ref()),
+            VarDeclOrExpr::VarDecl(var) => {
```
Comment (thantos) [inline src/parse.rs:340]: This can also be a binding pattern, I think?

**Review by thantos — APPROVED** [review]

File: src/parse.rs (hunk 2 above)
Comment (sam-goodwin) [reply src/parse.rs:340]: Do you have example syntax?

File: src/parse.rs [hunk 3]
```diff
@@ -180,126 +241,204 @@ impl ClosureDecorator {
...
+        let var = match &for_of.left {
+          VarDeclOrPat::VarDecl(var_decl) => {
+            // bind the for-of's variable declaration
+            // for (const item of ..)
+            //             ^
+            self.vm.bind_var_decl(var_decl);
+
+            self.parse_var_declarator(var_decl.decls.first().unwrap())
+          }
+          VarDeclOrPat::Pat(pat) => self.parse_pat(pat),
```
Comment (thantos) [inline src/parse.rs:423]: Patterns in ForIn and ForOf seem to be missing bind logic.

Comment (sam-goodwin) [reply src/parse.rs:423]: New names are only introduced by `var`, `const` or `let`
